/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#54606a",
        "tertiary-fixed-dim": "#ffb59b",
        "border-subtle": "#CED0D4",
        "tertiary-container": "#cb4400",
        "surface-container-highest": "#e0e3e6",
        "inverse-primary": "#b3c5ff",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e4f0",
        "on-secondary-container": "#5a6670",
        "on-primary-fixed-variant": "#003fa5",
        "surface-bright": "#f7f9fc",
        "surface-container": "#eceef1",
        "primary-container": "#0866ff",
        "surface-tint": "#0054d7",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "surface-card": "#FFFFFF",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#111d25",
        "on-surface-variant": "#424656",
        "text-secondary": "#65676B",
        "text-primary": "#1C1E21",
        "outline": "#727687",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f7",
        "on-tertiary-fixed-variant": "#812800",
        "on-error": "#ffffff",
        "outline-variant": "#c2c6d8",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#fff7f5",
        "success": "#31A24C",
        "surface-container-high": "#e6e8eb",
        "error": "#F02849",
        "background": "#f7f9fc",
        "on-secondary-fixed-variant": "#3d4852",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#e0e3e6",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcf",
        "on-primary-fixed": "#00184a",
        "secondary-container": "#d8e4f0",
        "secondary-fixed-dim": "#bcc8d3",
        "on-tertiary-fixed": "#380d00",
        "surface-dim": "#d8dadd",
        "on-primary-container": "#f9f7ff",
        "tertiary": "#a13400",
        "surface": "#f7f9fc",
        "primary": "#0050cd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "16px",
        "margin-desktop": "24px",
        "unit": "4px",
        "max-width-feed": "680px",
        "max-width-container": "1280px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
